<a href="https://colab.research.google.com/github/bunnybbear/bsc_dpdm22/blob/main/%5Bdataprep1%5D_property_estimator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

สรุปข้อมูลของนักประเมินแต่ละคน โดยพิจารณาจาก ความมั่นใจในการประเมิน ประเมินราคาซื้อ-ขาย ให้คะแนนทรัพย์

In [10]:
import pandas as pd

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
open_data1 = pd.read_excel('/content/drive/MyDrive/Data Mining/คำตอบนักประเมิน.xlsx')

In [13]:
open_data1.head()

,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,1,https://nayoo.co/khonkaen/posts/25,บ้านเดี่ยว,มั่นใจ,2700000.0,2500000.0,"5,000-15,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,100.0
1,2,https://nayoo.co/khonkaen/posts/25,บ้านเดี่ยว,มั่นใจ,2700000.0,2700000.0,"โครงการนี้ราคาเสนอขาย 2,500,000-3,000,000 บาท/...",NaN,4 ขายได้ ใช้ระยะเวลา 4 - 6 เดือน,NaN,NaN,NaN,NaN,NaN
2,1,https://nayoo.co/khonkaen/posts/33,บ้านเดี่ยว,มั่นใจ,2600000.0,2200000.0,"5,000-15,000",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
3,2,https://nayoo.co/khonkaen/posts/33,บ้านเดี่ยว,มั่นใจ,2600000.0,2400000.0,"ราคาเสนอขายประมาณ 2,200,000 - 2,500,000 บาท/หลัง",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
4,1,https://nayoo.co/khonkaen/posts/495,บ้านเดี่ยว,มั่นใจ,5900000.0,5000000.0,"5,000-15,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN

In [20]:
all_P = set(list(open_data1['ID ผู้ประเมิน']))
all_P

{1, 2}

In [16]:
open_P1 = open_data1[open_data1['ID ผู้ประเมิน']==1]
open_P1

,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,1,https://nayoo.co/khonkaen/posts/25,บ้านเดี่ยว,มั่นใจ,2700000.0,2500000.0,"5,000-15,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,100.0
2,1,https://nayoo.co/khonkaen/posts/33,บ้านเดี่ยว,มั่นใจ,2600000.0,2200000.0,"5,000-15,000",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
4,1,https://nayoo.co/khonkaen/posts/495,บ้านเดี่ยว,มั่นใจ,5900000.0,5000000.0,"5,000-15,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
6,1,https://nayoo.co/khonkaen/posts/564,บ้านเดี่ยว,มั่นใจ,4400000.0,3500000.0,"5,000-18,000",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
8,1,https://nayoo.co/khonkaen/posts/566,บ้านเดี่ยว,มั่นใจ,2750000.0,2500000.0,"5,000-25,000",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,1,https://nayoo.co/khonkaen/posts/19495,บ้านเดี่ยว,มั่นใจ,5500000.0,4500000.0,"3,000-30,000 บาท/ตารางวา",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
156,1,https://nayoo.co/khonkaen/posts/19496,บ้านเดี่ยว,มั่นใจ,7911000.0,5200000.0,"3,000-30,000 บาท/ตารางวา",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
157,1,https://nayoo.co/khonkaen/posts/20,บ้านเดี่ยว,มั่นใจ,2000000.0,3600000.0,"3,000-30,000 บาท/ตารางวา",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN
158,1,https://nayoo.co/khonkaen/posts/31,บ้านเดี่ยว,มั่นใจ,4000000.0,4000000.0,"3,000-35,000 บาท/ตารางวา",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
159,1,https://nayoo.co/khonkaen/posts/570,บ้านเดี่ยว,มั่นใจ,1375000.0,1200000.0,"3,000-30,000 บาท/ตารางวา",NaN,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี,NaN,NaN,NaN,NaN,NaN

In [17]:
open_P2 = open_data1[open_data1['ID ผู้ประเมิน']==2]
open_P2

,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
1,2,https://nayoo.co/khonkaen/posts/25,บ้านเดี่ยว,มั่นใจ,2700000.0,2700000.0,"โครงการนี้ราคาเสนอขาย 2,500,000-3,000,000 บาท/...",NaN,4 ขายได้ ใช้ระยะเวลา 4 - 6 เดือน,NaN,NaN,NaN,NaN,NaN
3,2,https://nayoo.co/khonkaen/posts/33,บ้านเดี่ยว,มั่นใจ,2600000.0,2400000.0,"ราคาเสนอขายประมาณ 2,200,000 - 2,500,000 บาท/หลัง",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
5,2,https://nayoo.co/khonkaen/posts/495,บ้านเดี่ยว,มั่นใจ,5900000.0,9000000.0,"โซนนี้ราคาซื้อขาย ประมาณ 10,000-20,000 บาท/ตาร...",NaN,5 ขายง่าย ใช้ระยะเวลา 1 - 3 เดือน,NaN,NaN,NaN,NaN,NaN
7,2,https://nayoo.co/khonkaen/posts/564,บ้านเดี่ยว,มั่นใจ,4400000.0,3700000.0,"เสนอขาย 3,500,000 - 4,200,000 บาท/หลัง",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
9,2,https://nayoo.co/khonkaen/posts/566,บ้านเดี่ยว,มั่นใจ,2750000.0,2500000.0,"ราคาเสนอขาย 2,000,0000 - 2,800,000 บาท/หลัง",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,2,https://nayoo.co/khonkaen/posts/19495,บ้านเดี่ยว,มั่นใจ,5500000.0,5000000.0,"ราคาเสนอขาย 20,000-30,000 บาท/ตารางวา",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
186,2,https://nayoo.co/khonkaen/posts/19496,บ้านเดี่ยว,มั่นใจ,7911000.0,7400000.0,"ราคาเสนอขาย 20,000 - 30,000 บาท/ตารางวา",NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
187,2,https://nayoo.co/khonkaen/posts/20,บ้านเดี่ยว,มั่นใจ,2000000.0,2500000.0,ราคาเสนอขาย 2.2-3.0 ล้านบาท/หลัง,NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
188,2,https://nayoo.co/khonkaen/posts/31,บ้านเดี่ยว,มั่นใจ,4000000.0,3900000.0,ราคาเสนอขาย 3.5-4.0ล้านบาท/หลัง,NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN
189,2,https://nayoo.co/khonkaen/posts/570,บ้านเดี่ยว,มั่นใจ,1375000.0,1400000.0,ราคาเสนอขาย 1.2-1.5 ล้านบาท/หลัง,NaN,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน,NaN,NaN,NaN,NaN,NaN

#พิจารณาผู้ประเมินคนที่ 1

In [21]:
dataP1 = open_P1[['ID ผู้ประเมิน','ความมั่นใจในการเมินราคาทรัพย์','ประเมินราคาซื้อ-ขาย','ให้คะแนนทรัพย์']]
dataP1.head()

,ID ผู้ประเมิน,ความมั่นใจในการเมินราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ให้คะแนนทรัพย์
0,1,มั่นใจ,2500000.0,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
2,1,มั่นใจ,2200000.0,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
4,1,มั่นใจ,5000000.0,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
6,1,มั่นใจ,3500000.0,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
8,1,มั่นใจ,2500000.0,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน

In [23]:
dataP1.describe()

       ID ผู้ประเมิน  ประเมินราคาซื้อ-ขาย
count          100.0         1.000000e+02
mean             1.0         3.938500e+06
std              0.0         2.368553e+06
min              1.0         6.000000e+05
25%              1.0         2.775000e+06
50%              1.0         3.600000e+06
75%              1.0         4.500000e+06
max              1.0         1.600000e+07

In [26]:
dataP1E = dataP1['ความมั่นใจในการเมินราคาทรัพย์']
dataP1E

0      มั่นใจ
2      มั่นใจ
4      มั่นใจ
6      มั่นใจ
8      มั่นใจ
        ...
155    มั่นใจ
156    มั่นใจ
157    มั่นใจ
158    มั่นใจ
159    มั่นใจ
Name: ความมั่นใจในการเมินราคาทรัพย์, Length: 100, dtype: object

In [34]:
dataP1E = dataP1[dataP1['ความมั่นใจในการเมินราคาทรัพย์']=='มั่นใจ'].count()
dataP1E

ID ผู้ประเมิน                    100
ความมั่นใจในการเมินราคาทรัพย์    100
ประเมินราคาซื้อ-ขาย              100
ให้คะแนนทรัพย์                   100
dtype: int64

In [42]:
#จากคำสั่ง dataP1.describe มีจำนวนข้อมูลอยู่ 100 และจาก dataP1E ผู้ประเมินคนที่ 1 ได้รับความมั่นใจ 100
PC1 = (100/100)*100;
PC1

100.0

In [40]:
dataP1['ให้คะแนนทรัพย์'].value_counts()

2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี    54
3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน     43
4 ขายได้ ใช้ระยะเวลา 4 - 6 เดือน       2
1 ขายไม่ได้แน่นอน                      1
Name: ให้คะแนนทรัพย์, dtype: int64

#พิจารณาผู้ประเมินคนที่ 2

In [22]:
dataP2 = open_P2[['ID ผู้ประเมิน','ความมั่นใจในการเมินราคาทรัพย์','ประเมินราคาซื้อ-ขาย','ให้คะแนนทรัพย์']]
dataP2.head()

,ID ผู้ประเมิน,ความมั่นใจในการเมินราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ให้คะแนนทรัพย์
1,2,มั่นใจ,2700000.0,4 ขายได้ ใช้ระยะเวลา 4 - 6 เดือน
3,2,มั่นใจ,2400000.0,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
5,2,มั่นใจ,9000000.0,5 ขายง่าย ใช้ระยะเวลา 1 - 3 เดือน
7,2,มั่นใจ,3700000.0,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
9,2,มั่นใจ,2500000.0,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน

In [24]:
dataP2.describe()

       ID ผู้ประเมิน  ประเมินราคาซื้อ-ขาย
count           90.0         8.900000e+01
mean             2.0         4.153258e+06
std              0.0         2.386901e+06
min              2.0         9.900000e+05
25%              2.0         2.600000e+06
50%              2.0         3.900000e+06
75%              2.0         4.900000e+06
max              2.0         1.700000e+07

In [31]:
dataP2E = dataP2[dataP2['ความมั่นใจในการเมินราคาทรัพย์']=='มั่นใจ'].count()
dataP2E

ID ผู้ประเมิน                    89
ความมั่นใจในการเมินราคาทรัพย์    89
ประเมินราคาซื้อ-ขาย              89
ให้คะแนนทรัพย์                   89
dtype: int64

In [43]:
#จากคำสั่ง dataP2.describe มีจำนวนข้อมูลอยู่ 90 และจาก dataP2E ผู้ประเมินคนที่ 2 ได้รับความมั่นใจ 89
PC2 = (89/90)*100;
PC2

98.88888888888889

In [46]:
#อีกวิธี
dataP2['ความมั่นใจในการเมินราคาทรัพย์'].value_counts()

มั่นใจ       89
ไม่มั่นใจ     1
Name: ความมั่นใจในการเมินราคาทรัพย์, dtype: int64

In [41]:
dataP2['ให้คะแนนทรัพย์'].value_counts()

3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน     64
4 ขายได้ ใช้ระยะเวลา 4 - 6 เดือน      23
5 ขายง่าย ใช้ระยะเวลา 1 - 3 เดือน      1
2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี     1
Name: ให้คะแนนทรัพย์, dtype: int64

#เปรียบเทียบความแตกต่างในการประเมินราคาทรัพย์แต่ละทรัพย์ของนักประเมินแต่ละคนและของราคาตั้งขาย ใช้ MAPE เป็นเกณฑ์ในการเปรียบเทียบ

In [47]:
from sklearn.metrics import mean_absolute_percentage_error

In [54]:
SCP1 = open_P1[['post id','ราคาทรัพย์','ประเมินราคาซื้อ-ขาย']]
SCP1

                                   post id  ราคาทรัพย์  ประเมินราคาซื้อ-ขาย
0       https://nayoo.co/khonkaen/posts/25   2700000.0            2500000.0
2       https://nayoo.co/khonkaen/posts/33   2600000.0            2200000.0
4      https://nayoo.co/khonkaen/posts/495   5900000.0            5000000.0
6      https://nayoo.co/khonkaen/posts/564   4400000.0            3500000.0
8      https://nayoo.co/khonkaen/posts/566   2750000.0            2500000.0
..                                     ...         ...                  ...
155  https://nayoo.co/khonkaen/posts/19495   5500000.0            4500000.0
156  https://nayoo.co/khonkaen/posts/19496   7911000.0            5200000.0
157     https://nayoo.co/khonkaen/posts/20   2000000.0            3600000.0
158     https://nayoo.co/khonkaen/posts/31   4000000.0            4000000.0
159    https://nayoo.co/khonkaen/posts/570   1375000.0            1200000.0

[100 rows x 3 columns]

In [55]:
SCP2 = open_P2[['post id','ราคาทรัพย์','ประเมินราคาซื้อ-ขาย']]
SCP2

                                   post id  ราคาทรัพย์  ประเมินราคาซื้อ-ขาย
1       https://nayoo.co/khonkaen/posts/25   2700000.0            2700000.0
3       https://nayoo.co/khonkaen/posts/33   2600000.0            2400000.0
5      https://nayoo.co/khonkaen/posts/495   5900000.0            9000000.0
7      https://nayoo.co/khonkaen/posts/564   4400000.0            3700000.0
9      https://nayoo.co/khonkaen/posts/566   2750000.0            2500000.0
..                                     ...         ...                  ...
185  https://nayoo.co/khonkaen/posts/19495   5500000.0            5000000.0
186  https://nayoo.co/khonkaen/posts/19496   7911000.0            7400000.0
187     https://nayoo.co/khonkaen/posts/20   2000000.0            2500000.0
188     https://nayoo.co/khonkaen/posts/31   4000000.0            3900000.0
189    https://nayoo.co/khonkaen/posts/570   1375000.0            1400000.0

[90 rows x 3 columns]

In [58]:
SCP12 = SCP2.merge(SCP1, left_on='post id', right_on='post id')
SCP12

,post id,ราคาทรัพย์_x,ประเมินราคาซื้อ-ขาย_x,ราคาทรัพย์_y,ประเมินราคาซื้อ-ขาย_y
0,https://nayoo.co/khonkaen/posts/25,2700000.0,2700000.0,2700000.0,2500000.0
1,https://nayoo.co/khonkaen/posts/33,2600000.0,2400000.0,2600000.0,2200000.0
2,https://nayoo.co/khonkaen/posts/495,5900000.0,9000000.0,5900000.0,5000000.0
3,https://nayoo.co/khonkaen/posts/564,4400000.0,3700000.0,4400000.0,3500000.0
4,https://nayoo.co/khonkaen/posts/566,2750000.0,2500000.0,2750000.0,2500000.0
...,...,...,...,...,...
85,https://nayoo.co/khonkaen/posts/19495,5500000.0,5000000.0,5500000.0,4500000.0
86,https://nayoo.co/khonkaen/posts/19496,7911000.0,7400000.0,7911000.0,5200000.0
87,https://nayoo.co/khonkaen/posts/20,2000000.0,2500000.0,2000000.0,3600000.0
88,https://nayoo.co/khonkaen/posts/31,4000000.0,3900000.0,4000000.0,4000000.0
89,https://nayoo.co/khonkaen/posts/570,1375000.0,1400000.0,1375000.0,1200000.0